apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieticket-api
  namespace: movieticket
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movieticket-api
  template:
    metadata:
      labels:
        app: movieticket-api
    spec:
      containers:
        - name: api
          image: keerthi1110/movieticket-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: movieticket-config
            - secretRef:
                name: movieticket-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
