apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieticket-frontend
  namespace: movieticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movieticket-frontend
  template:
    metadata:
      labels:
        app: movieticket-frontend
    spec:
      containers:
      - name: frontend
        image: keerthi1110/movieticket-frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

      volumes:
      - name: nginx-config
        configMap:
          name: movieticket-nginx-config
