apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieticket-mongo
  labels:
    app: movieticket-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieticket-mongo
  template:
    metadata:
      labels:
        app: movieticket-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: movieticket-mongo
spec:
  selector:
    app: movieticket-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
