apiVersion: v1
kind: Service
metadata:
  name: movieticket-api
  namespace: movieticket
spec:
  type: ClusterIP
  selector:
    app: movieticket-api
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: movieticket-frontend
  namespace: movieticket
spec:
  type: NodePort
  selector:
    app: movieticket-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32430
